# version: '3.8'

# services:
#   db:
#     image: postgres:latest
#     container_name: careem-system-db
#     environment:
#       POSTGRES_USER: Wassem
#       POSTGRES_PASSWORD: password
#       PGDATA: /var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - app-db

#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     networks:
#       - app-db

# networks:
#   app-db:
#     driver: bridge

version: '3.8'

services:
  maven:
    build: ./Dockerfile.maven
    container_name: maven

  app:
    build: ./Dockerfile.openjdk
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build: ./Dockerfile.psql
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Wassem
      POSTGRES_PASSWORD: password
