version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: careem-system
    environment:
        POSTGRES_USER: Wassem
        POSTGRES_PASSWORD: password
        PGDATA: /var/lib/postgresql/data
#    volumes:
#        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5334:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
#volumes:
#  postgres-data:
