server:
  port: 3012
#  address: localhost

spring:
  application:
    name: RideShare
  datasource:
    url: jdbc:postgresql://rideshare_dp:5432/rideshare
    username: postgres
    password: Wassem7676.tn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


    #uploading direction
  file:
    upload-dir

  mail:
    host: smtp.gmail.com
    port: 587
    username: wasee.tenbakji@gmail.com  # Replace with your actual Gmail address
    password: uphkmwhxuoapuuwi  # Replace with your actual Gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # This is the correct property name for enabling TLS
  servlet:
    multipart:
      max-request-size: 1650MB
      max-file-size: 1650MB
